language: node_js
node_js:
  - '10'

os: linux
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

jobs:
  fast_finish: true

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint
        - npm run test:all

install:
  - npm install
